language: generic
sudo: required
serivces:
  - docker

before_install:
  - docker build -t aom87shortcut/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aom87shortcut/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-368987284475"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
